CREATE TABLE IF NOT EXISTS tblAdminUsers(
    AdminUsersID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    SuperUser BOOLEAN NOT NULL,
    Foreign Key (UserID) REFERENCES tblUser (UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tblCreateTables(
    CreateTablesID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AdminID INT NOT NULL,
    TableName VARCHAR(100) NOT NULL,
    Foreign Key (AdminID) REFERENCES tblUser (UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tblEditTables(
    EditTablesID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AdminID INT NOT NULL,
    TableName VARCHAR(100) NOT NULL,
    Foreign Key (AdminID) REFERENCES tblUser (UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tblDeleteTables(
    DeleteTablesID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AdminID INT NOT NULL,
    TableName VARCHAR(100) NOT NULL,
    Foreign Key (AdminID) REFERENCES tblUser (UserID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tblViewTables(
    ViewTablesID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AdminID INT NOT NULL,
    TableName VARCHAR(100) NOT NULL,
    Foreign Key (AdminID) REFERENCES tblUser (UserID) ON DELETE CASCADE
);